name: wardolphin
author: Brianna
markdown: kramdown
theme: jekyll-theme-minimal
logo: logo.png
twitter: https://twitter.com/briannajoym
linkedin: https://www.linkedin.com/in/briannajoy/
project_tagline: https://wardolphin.party/blog/
plugins:
  - jekyll-feed
title: Wardolphin's Blog
description: Friendly hacker Trust me
author: Brianna

