name: wardolphin
markdown: kramdown
theme: jekyll-theme-minimal
logo: logo.png
twitter: https://twitter.com/briannajoym
linkedin: https://www.linkedin.com/in/briannajoy/
project_tagline: https://wardolphin.party/blog/
